"""Shared chart styling for factory decks — identity-driven, deterministic, on-brand.

Used from a project's deck/charts/make_charts.py:

    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "scripts"))
    import chartkit as ck

    kit = ck.Kit()                        # reads deck/identity.json, loads fonts, sets rcParams
    fig, ax = kit.figure()                # 12.8 x 6.4 in — a 2:1 plot under a slide headline
    ax.bar(labels, values, color=kit.emphasis(labels, highlight="CRITICAL"))
    kit.title(fig, "Exploitation triples from HIGH to CRITICAL", "Share later listed in CISA KEV, % of CVEs")
    kit.source(fig, "Source: CISA KEV, NIST NVD · n = 20,149 CVEs published in 2021")
    kit.save(fig, "02-severity-bands")    # → deck/charts/02-severity-bands.svg
    kit.figures.add("CRITICAL vs MEDIUM multiple", 2.55 / 0.33, "{:.1f}x")
    kit.figures.write()                   # → deck/charts/FIGURES.md

Run from the project directory (scripts/build_charts.sh does). Styling lives here so
chart scripts only express what to plot, and every chart in a deck looks like it
belongs to that deck.
"""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib import font_manager  # noqa: E402

FONT_CACHE = Path.home() / ".cache" / "agent-factory-fonts"


def _fetch_font(family: str, weights: tuple[int, ...] = (400, 600, 700)) -> bool:
    """Download a Google Fonts family as TTF and register it with matplotlib.

    Returns False (and charts fall back to DejaVu Sans) if the network or family is
    unavailable, so a font hiccup degrades the look instead of failing the build.
    """
    target = FONT_CACHE / re.sub(r"\W+", "-", family.lower())
    files = sorted(target.glob("*.ttf")) if target.exists() else []
    if not files:
        try:
            query = family.replace(" ", "+") + ":wght@" + ";".join(map(str, weights))
            req = urllib.request.Request(f"https://fonts.googleapis.com/css2?family={query}",
                                         headers={"User-Agent": "Mozilla/4.0"})  # plain UA → TTF, not woff2
            css = urllib.request.urlopen(req, timeout=20).read().decode()
            urls = re.findall(r"url\((https://[^)]+\.ttf)\)", css)
            if not urls:
                return False
            target.mkdir(parents=True, exist_ok=True)
            for i, url in enumerate(dict.fromkeys(urls)):
                path = target / f"{i}.ttf"
                path.write_bytes(urllib.request.urlopen(url, timeout=20).read())
                files.append(path)
        except Exception as exc:  # network, 400 for unknown family, etc.
            print(f"chartkit: couldn't load font {family!r} ({exc}); falling back to DejaVu Sans")
            return False
    for path in files:
        font_manager.fontManager.addfont(str(path))
    return True


def _mix(a: str, b: str, t: float) -> str:
    """Blend hex a toward b by t (0..1) — used for recessive gridlines."""
    ca = [int(a[i:i + 2], 16) for i in (1, 3, 5)]
    cb = [int(b[i:i + 2], 16) for i in (1, 3, 5)]
    return "#" + "".join(f"{round(x + (y - x) * t):02x}" for x, y in zip(ca, cb))


class Figures:
    """Derived figures a deck quotes, written to FIGURES.md by the chart script itself."""

    def __init__(self, path: Path) -> None:
        self.path, self.rows = path, []

    def add(self, label: str, value: float | int | str, fmt: str = "{}") -> str:
        text = fmt.format(value)
        self.rows.append((label, text))
        return text

    def write(self) -> None:
        lines = ["# Derived figures", "",
                 "Written by deck/charts/make_charts.py from the committed data. Regenerated by the",
                 "workflow before the provenance gate, so every figure here is computed, not typed.", ""]
        lines += [f"- {label}: {text}" for label, text in self.rows]
        self.path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class Kit:
    def __init__(self, identity_path: str | Path = "deck/identity.json", out_dir: str | Path = "deck/charts") -> None:
        self.identity = json.loads(Path(identity_path).read_text(encoding="utf-8"))
        c = self.identity["colors"]
        self.bg, self.ink, self.muted = c["background"], c["ink"], c["muted"]
        self.accent, self.context, self.categorical = c["accent"], c["context"], list(c["categorical"])
        self.out = Path(out_dir)
        self.out.mkdir(parents=True, exist_ok=True)
        self.figures = Figures(self.out / "FIGURES.md")

        fonts = self.identity.get("fonts", {})
        body = fonts.get("body", "DejaVu Sans")
        family = [body] if _fetch_font(body) else []
        display = fonts.get("display")
        self.display_family = [display] if display and display != body and _fetch_font(display) else family

        plt.rcParams.update({
            "font.family": family + ["DejaVu Sans"],
            "font.size": 15,
            "svg.fonttype": "path",           # outlines: identical in HTML, PDF, and PPTX
            "svg.hashsalt": "agent-factory",  # deterministic ids — no churn between runs
            "figure.figsize": (12.8, 6.4),
            "figure.facecolor": "none",       # transparent: the slide's own background shows
            "axes.facecolor": "none",
            "savefig.transparent": True,
            "text.color": self.ink,
            "axes.labelcolor": self.muted,
            "axes.edgecolor": _mix(self.muted, self.bg, 0.35),
            "axes.linewidth": 1.0,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.titlesize": 22,
            "axes.labelsize": 15,
            "axes.prop_cycle": matplotlib.cycler(color=self.categorical),
            "axes.grid": False,
            "grid.color": _mix(self.muted, self.bg, 0.7),
            "grid.linewidth": 0.8,
            "grid.linestyle": "-",            # solid hairlines, never dashed
            "xtick.color": self.muted, "ytick.color": self.muted,
            "xtick.labelsize": 15, "ytick.labelsize": 15,
            "xtick.major.size": 0, "ytick.major.size": 0,
            "legend.frameon": False, "legend.fontsize": 15,
            "lines.linewidth": 2.5,
            "patch.linewidth": 0,
        })

    # ── color helpers ──
    def emphasis(self, labels: list, highlight) -> list[str]:
        """Accent for the highlighted label(s), context gray for the rest."""
        keep = set(highlight) if isinstance(highlight, (list, tuple, set)) else {highlight}
        return [self.accent if label in keep else self.context for label in labels]

    def sequential(self, n: int) -> list[str]:
        """n steps of one hue, from a light tint toward the accent."""
        return [_mix(_mix(self.accent, self.bg, 0.8), self.accent, i / max(n - 1, 1)) for i in range(n)]

    # ── anatomy ──
    def figure(self, size: tuple[float, float] = (12.8, 6.4), **kwargs):
        fig, ax = plt.subplots(figsize=size, **kwargs)
        # Default margins reserve ~1.6 in for a y-axis; charts here often hide it, which
        # left the plot floating right of the title. Tight margins; bbox_inches="tight"
        # on save still includes any tick labels that extend past them.
        fig.subplots_adjust(left=0.06, right=0.98, top=0.9, bottom=0.12)
        return fig, ax

    def title(self, fig, finding: str, subtitle: str = "") -> None:
        """Left-aligned headline that states the finding, plus unit/scope underneath."""
        fig.text(0.0, 1.06 if subtitle else 1.02, finding, ha="left", va="bottom", fontsize=26,
                 fontweight="bold", color=self.ink, family=self.display_family + ["DejaVu Sans"],
                 transform=fig.transFigure)
        if subtitle:
            fig.text(0.0, 1.01, subtitle, ha="left", va="bottom", fontsize=16, color=self.muted,
                     transform=fig.transFigure)

    def source(self, fig, text: str) -> None:
        fig.text(0.0, -0.06, text, ha="left", va="top", fontsize=12, color=self.muted, transform=fig.transFigure)

    def label(self, ax, x, y, text: str, color: str | None = None, **kwargs) -> None:
        """A direct label — use selectively, for the point that matters."""
        ax.annotate(text, (x, y), xytext=kwargs.pop("xytext", (6, 0)), textcoords="offset points",
                    fontsize=kwargs.pop("fontsize", 16), fontweight=kwargs.pop("fontweight", "bold"),
                    color=color or self.ink, va=kwargs.pop("va", "center"), **kwargs)

    def save(self, fig, name: str) -> Path:
        path = self.out / f"{name}.svg"
        fig.savefig(path, format="svg", bbox_inches="tight", pad_inches=0.25, metadata={"Date": None})
        plt.close(fig)
        print(f"chartkit: wrote {path}")
        return path
